### PR TITLE
parity with new function signatures fixes #7

### LINKED ISSUE #7: Update for parity with changes in record functions
Plugin does not build with coredns main branch, I tried at coredns commit a929b0b1ecbb0f87b0bd0cd0a40ce38893dce9c0

```
lauralorenz@lauralorenz:~/coredns/coredns$ make
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=a929b0b1-dirty" -o coredns
github.com/coredns/multicluster
# github.com/coredns/multicluster
../../go/pkg/mod/github.com/coredns/multicluster@v0.0.0-20211130154347-488880e11fc0/multicluster.go:131:18: assignment mismatch: 2 variables but plugin.A returns 3 values
../../go/pkg/mod/github.com/coredns/multicluster@v0.0.0-20211130154347-488880e11fc0/multicluster.go:133:18: assignment mismatch: 2 variables but plugin.AAAA returns 3 values
../../go/pkg/mod/github.com/coredns/multicluster@v0.0.0-20211130154347-488880e11fc0/multicluster.go:135:18: assignment mismatch: 2 variables but plugin.TXT returns 3 values
../../go/pkg/mod/github.com/coredns/multicluster@v0.0.0-20211130154347-488880e11fc0/multicluster.go:148:12: assignment mismatch: 2 variables but plugin.A returns 3 values
make: *** [Makefile:16: coredns] Error 2
```

Appears to be due to function signature changes for records in https://github.com/coredns/coredns/pull/4715 meaning this plugin is currently incompatible as of coredns 1.9.1.

### PR DESCRIPTION
**Pull request by lauralorenz**
fixes #7

### CODE REVIEW

**Comment by xh4n3** [comment]
Hi @lauralorenz , are you still on this pr? 😃 
I can help to fix if you're not available, please let me know, thanks!

**Comment by lauralorenz** [comment]
Hi @xh4n3, thanks for the bump!! This is now ready for review, and I double checked it with the latest coredns commit aka after the 1.9.3 release as well 👍 

The manual testing directions I followed are in this gist: https://gist.github.com/lauralorenz/b40fd12a944c12068213ce85f8a04e68

cc and assigning @chrisohaver for review or to delegate

**Comment by lauralorenz** [comment]
Does this thing use the bot? 🙃 

/assign @chrisohaver

**Review by chrisohaver — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
