### PR TITLE
Fix for k8s.io/apimachinery@v0.24.0

### PR DESCRIPTION
**Pull request by runakash**
Fixes https://github.com/coredns/multicluster/issues/9

### CODE REVIEW

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Since Go modules are not used in this repo, we may want to implement both methods, so the Object interface would be implemented in apimachinery versions before and after v0.24.0.

**Comment by runakash** [comment]
> Since Go modules are not used in this repo, we may want to implement both methods, so the Object interface would be implemented in apimachinery versions before and after v0.24.0.

Makes sense. Seems like it will be simpler to onboard go module. What do you think?

**Comment by chrisohaver** [comment]
> Makes sense. Seems like it will be simpler to onboard go module. What do you think?

Simpler than not deleting two functions?  Maybe I'm not seeing the whole picture.

**Review by chrisohaver — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
